version: '3.8'

services:
  # Config Server
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network

  # Service Discovery
  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - config-server
    networks:
      - spring-cloud-network

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-cloud-network

  # Kafka + Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - spring-cloud-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spring-cloud-network

  # User Service
  user-service:
    build: ./user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - config-server
      - service-discovery
      - postgres
      - kafka
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network

  # Notification Service
  notification-service:
    build: ./notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - config-server
      - service-discovery
      - kafka
    ports:
      - "8082:8082"
    networks:
      - spring-cloud-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - config-server
      - service-discovery
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

volumes:
  postgres_data:

networks:
  spring-cloud-network:
    driver: bridge